### PR TITLE
revamp: pull request template

### PR DESCRIPTION
**Pull request by Awemeter**
# Title

### Discord username

Awemeter#7919
## References used

N/A
## Images and/or videos of changes (if needed)

N/A
## Additional comments

N/A

**QA testing coming soon**

### CODE REVIEW

**Comment by scoopscode** [comment]
Is this good to merge @Awemeter ?

**Comment by scoopscode** [comment]
@Awemeter update on this?

**Comment by Spherrrical** [comment]
Can we get another update on this or do we close it?

**Comment by Awemeter** [comment]
Yo can close i cant really make a pr template before we have the plane ready ya know

**Pull request closed without merging**
